### ISSUE TITLE
any idea on how to fix this issue?

### ISSUE THREAD

**Issue by VituArtz** [Arecurius0/UniqueLootHelper#1]
![issue](https://github.com/Arecurius0/UniqueLootHelper/assets/70963981/666b993a-ebd1-4de0-90e8-5bbfe67759b6)

**Comment by going1356** [comment]
Haven't found a solution to the problem yet? I have the same error

**Comment by Arecurius0** [comment]
This plugin is super outdated at this point and its functionality has been included in NinjaPricer. So use that instead. Gonna archive the repo at this Point
